---
title: ResultError (v0.19)
description: API reference for qiskit.result.ResultError in qiskit v0.19
in_page_toc_min_heading_level: 1
python_api_type: exception
python_api_name: qiskit.result.ResultError
---

# ResultError

<Class id="qiskit.result.ResultError" isDedicatedPage={true} github="https://github.com/qiskit/qiskit/tree/stable/0.14/qiskit/result/exceptions.py" signature="ResultError(error)" modifiers="exception">
  Exceptions raised due to errors in result output.

  It may be better for the Qiskit API to raise this exception.

  **Parameters**

  **error** (*dict*) –

  This is the error record as it comes back from the API. The format is like:

  ```python
  error = {'status': 403,
           'message': 'Your credits are not enough.',
           'code': 'MAX_CREDITS_EXCEEDED'}
  ```

  Set the error message.

  ### with\_traceback

  <Function id="qiskit.result.ResultError.with_traceback" signature="with_traceback()">
    Exception.with\_traceback(tb) – set self.\_\_traceback\_\_ to tb and return self.
  </Function>
</Class>

