---
title: IBMQManagedResultDataNotAvailable
description: API reference for qiskit.providers.ibmq.managed.IBMQManagedResultDataNotAvailable
in_page_toc_min_heading_level: 1
python_api_type: exception
python_api_name: qiskit.providers.ibmq.managed.IBMQManagedResultDataNotAvailable
---

<span id="qiskit-providers-ibmq-managed-ibmqmanagedresultdatanotavailable" />

# qiskit.providers.ibmq.managed.IBMQManagedResultDataNotAvailable

<Class id="qiskit.providers.ibmq.managed.IBMQManagedResultDataNotAvailable" isDedicatedPage={true} github="https://github.com/qiskit/qiskit-ibmq-provider/tree/stable/0.12/qiskit/providers/ibmq/managed/exceptions.py" signature="IBMQManagedResultDataNotAvailable(*message)" modifiers="exception">
  Errors raised when result data is not available.

  Set the error message.

  ### with\_traceback

  <Function id="qiskit.providers.ibmq.managed.IBMQManagedResultDataNotAvailable.with_traceback" signature="with_traceback()">
    Exception.with\_traceback(tb) â€“ set self.\_\_traceback\_\_ to tb and return self.
  </Function>
</Class>

