---
title: CredentialsNotFoundError
description: API reference for qiskit.providers.ibmq.credentials.CredentialsNotFoundError
in_page_toc_min_heading_level: 1
python_api_type: exception
python_api_name: qiskit.providers.ibmq.credentials.CredentialsNotFoundError
---

<span id="qiskit-providers-ibmq-credentials-credentialsnotfounderror" />

# qiskit.providers.ibmq.credentials.CredentialsNotFoundError

<Class id="qiskit.providers.ibmq.credentials.CredentialsNotFoundError" isDedicatedPage={true} github="https://github.com/qiskit/qiskit-ibmq-provider/tree/stable/0.12/qiskit/providers/ibmq/credentials/exceptions.py" signature="CredentialsNotFoundError(*message)" modifiers="exception">
  Errors raised when the credentials are not found.

  Set the error message.

  ### with\_traceback

  <Function id="qiskit.providers.ibmq.credentials.CredentialsNotFoundError.with_traceback" signature="with_traceback()">
    Exception.with\_traceback(tb) â€“ set self.\_\_traceback\_\_ to tb and return self.
  </Function>
</Class>

