---
title: IBMQAccountCredentialsNotFound
description: API reference for qiskit.providers.ibmq.IBMQAccountCredentialsNotFound
in_page_toc_min_heading_level: 1
python_api_type: exception
python_api_name: qiskit.providers.ibmq.IBMQAccountCredentialsNotFound
---

<span id="qiskit-providers-ibmq-ibmqaccountcredentialsnotfound" />

# qiskit.providers.ibmq.IBMQAccountCredentialsNotFound

<Class id="qiskit.providers.ibmq.IBMQAccountCredentialsNotFound" isDedicatedPage={true} github="https://github.com/qiskit/qiskit-ibmq-provider/tree/stable/0.12/qiskit/providers/ibmq/exceptions.py" signature="IBMQAccountCredentialsNotFound(*message)" modifiers="exception">
  Errors raised when credentials are not found.

  Set the error message.

  ### with\_traceback

  <Function id="qiskit.providers.ibmq.IBMQAccountCredentialsNotFound.with_traceback" signature="with_traceback()">
    Exception.with\_traceback(tb) â€“ set self.\_\_traceback\_\_ to tb and return self.
  </Function>
</Class>

